### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by shuichis929** [shuichis929/protospace-38456#1]
https://protospace-38456.herokuapp.com/

**Comment by motomuun** [comment]
@shuichis929 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**ユーザー詳細機能**

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
下記画像の赤枠の「ユーザー名さん」に、正しいユーザー名が表示されるように修正をお願いします。
<img width="1440" alt="スクリーンショット 2022-09-21 15 54 33" src="https://user-images.githubusercontent.com/65059944/191435310-c85d52f2-f556-4505-8b94-4f8b0f4f64f1.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shuichis929** [comment]
ご確認、ご指摘頂きありがとうございます。
指摘箇所の修正をいたしましたので、再度ご確認頂ければ幸いでございます。
よろしくお願い致します。

**Comment by shodai-ito** [comment]
@shuichis929 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by shuichis929** [comment]
> @shuichis929 さん、ご提出ありがとうございます‼︎ 動作の確認をしたところ、修正していただきたい箇所がございました。 以下のご確認をお願いします！
> 
> [修正依頼箇所] **ユーザー詳細機能**
> 
> * [ ]  **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
>   下記画像の赤枠の「ユーザー名さん」に、正しいユーザー名が表示されるように修正をお願いします。
> 
> <img alt="スクリーンショット 2022-09-21 15 54 33" width="1440" src="https://user-images.githubusercontent.com/65059944/191435310-c85d52f2-f556-4505-8b94-4f8b0f4f64f1.png">
> 
> 修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！ ※新しいissueを作っていただく必要はございません。 ※質問等でコメントした場合も都度フォームのご提出をお願いします。 https://forms.gle/ZdLeprTTWhMA8aZA7
